### ISSUE TITLE
Error - 11200  - Version 2.5

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#186]
Msg | "An attempt to retrieve content from /yap2/meeting-search.php?Latitude=-33.8060158&Longitude=151.2947775 returned the HTTP status code 500"
-- | --
msg | "An attempt to retrieve content from /yap2/meeting-search.php?Latitude=-33.8060158&Longitude=151.2947775 returned the HTTP status code 500"
sourceComponent | "13700"
ErrorCode | "11200"
httpResponse | "500"
LogLevel | "ERROR"
url | "/yap2/meeting-search.php?Latitude=-33.8060158&Longitude=151.2947775"

**Comment by radius314** [comment]
redacted host names to avoid spammers

**Comment by radius314** [comment]
500 error isn't a timeout

**Comment by radius314** [comment]
need server error logs

**Comment by brustar64** [comment]
There's a bunch of different errors.

I'll provide more context when I touch down in Melbourne tonight.

Regards
Bruce

________________________________

**Comment by radius314** [comment]
Looking for your server logs.  Twilio doesn't know the root cause of the 500 error.

**Comment by radius314** [comment]
Not sure exactly what's going on.  The error logs you sent do not seem to indicate anything specifically.  Also, the errors are not isolated to a specific set of PHP pages.  Given the cross-cutting nature of these alarms and the fact that no other installations are reporting such issues, it leads me to believe that these are just TCP latency issues.  This is either caused by the network traffic requests from Twilio to your server, or your server itself.

**Comment by brustar64** [comment]
Multiple errors today 

![screen shot 2018-11-19 at 6 19 21 pm](https://user-images.githubusercontent.com/29008815/48694394-e84c6300-ec27-11e8-9888-3aba9ab310a4.png)

emailed YAP logs

**Comment by radius314** [comment]
Bruce the errors do not seem to be isolated to a given PHP endpoint.  This
leads me to believe that it's a hosting provider issue with latency.

**Comment by brustar64** [comment]
Thanks Danny

I'll follow up with them.

Regards
Bruce

________________________________
