### ISSUE TITLE
Meetings listed far away

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/yap#199]
I wonder if there’s a bug in yap. I was going to test and see if I put a note about a closed meeting it would print that note out. So I used a zip code of a meeting tomorrow night that’s closed and has a note. It only printed out one meeting close to the zip the first time. The others are 79 miles, 85 miles, 175 miles and 206 miles. I waited about an hour using the same zip and it still printed 2 meetings pretty far away.... (175 and 206 miles) It used to not spit out meetings so far away. Do I need to adjust some setting?

I'm using version 2.5.1
iphone 6+
same response on text and call.
![screenshot2](https://user-images.githubusercontent.com/15731404/48814512-a511f300-ed00-11e8-93ec-1dd1d56f122a.jpeg)

![screen shot](https://user-images.githubusercontent.com/15731404/48814263-c7efd780-ecff-11e8-92e4-ed475b4bf56f.jpg)

**Comment by lucy12187** [comment]
it seems like if there were no more meetings today near 38117 it would print out tomorrow's meetings... which it did the 2nd time i used the zip about an hour later.  step write in and doing this thing.

**Comment by radius314** [comment]
Can you email me your config.php and the access logs for that time period?

What time period was this SMS sent?

**Comment by radius314** [comment]
FYI this looks like it's working correctly.  This is the BMLT query that was executed: 

Zip 38117 geocodes to the latitude and longitude and gets passed to your root server as seen below.

[tennesee_root_server]/client_interface/json/?switcher=GetSearchResults&sort_results_by_distance=1&long_val=-89.901957&lat_val=35.1103341&geo_width=-50&weekdays=3

**Results** 
1) Lunch Bunch in Memphis, TN (filtered out because it started at Noon)
2) You + Me = We in Memphis, TN (filtered out because it started at 8 AM)
3) Simplicity is the Key in Memphis, TN  (filtered out because it started at 6:30 PM)
4) Clarity in Cordova, TN 8PM meeting (listed as 7 miles away) (1st result shown)

This is working as expected.

**Comment by lucy12187** [comment]
those are good.  but why did it list Clarksville, dickson, jackson dyersburg the first time I tried it?  plus clarksville is still in the 2nd one.

**Comment by radius314** [comment]
What time did you send those texts?

**Comment by lucy12187** [comment]
so i need to fix my settings or something so that it doesnt show meetings so far away.  don't you think?  i didn't really know there were those other settings we could add.  or maybe i knew at one time i just never thought i needed them since i'd never seen it do this before.

**Comment by radius314** [comment]
I have no opinion on how you configure your Yap instance here.
