### ISSUE TITLE
Import/Export feature for Volunteer list

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/yap#255]
We have a large database of Helpline volunteers and would like a database independent import export feature for the following reasons: 1) initial population, 2) backup purposes, 3) in case a new Yap release requires us to reenter the volunteer info, and 4) we are required to provide current volunteer lists to different service bodies.

**Comment by radius314** [comment]
#2 is satisfied by taking a backup of the MySQL database regularly.
#3 was never necessary since data is always compatible on a going forward basis.  There are no breaking changes introduced in the data process.

#1 is not a compelling enough reason at this point given the time and complexity to develop this feature.  Leaving the ticket open, but until there is mass appeal for this feature, it will not be introduced.

**Comment by Redguy1959** [comment]
#1- how about publishing enough info on the database "schema" and encoding so that someone else can do it? Like me.
  ----- Original Message -----

**Comment by radius314** [comment]
I can publish some information about how the base information is constructed.  The schedules are encoded as base64.  This was done to make it easier to pass things over HTTPS (not for security reasons).  TLS is already encrypted.

**Comment by radius314** [comment]
You can see the data of the schedules by running a base64 decoder on it.

**Comment by pjaudiomv** [comment]
Yea ya can.
