### ISSUE TITLE
volunteer data not showing up on map

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#371]
volunteer data is displaying in the table and tally but no pins showing up on map. this happens if i select my area or region and use recursive, or select all. I am on 3.6.2, this worked on 3.6.1.

**Comment by pjaudiomv** [comment]
seems the only way I can view volunteer data is by logging in with a admin account that has access to every service body in server. I am on sezf. also its weird alabama only has orange pins/tally. all other service bodies only have green ones.

**Comment by radius314** [comment]
Will need a little more information than what was presented here.  These are very vague details.

**Comment by radius314** [comment]
I see that you emailed the database dump over.  I can see the issue, investigating what's going on.

**Comment by radius314** [comment]
I see what is going on.  The reason you do not see any volunteer searches mapped out is because there are no coordinates for those volunteer lookups.  These are cases where someone directly dialed the service body.  The only volunteer lookups you will see are those related to a number where a location lookup is made for volunteer searches.  You aren't seeing things that were general anymore because of the fix for #364.

**Comment by pjaudiomv** [comment]
omg, thanks for clarifying that makes sense.

**Comment by radius314** [comment]
Open to any suggestions on how to better handle this if you have any.
