### ISSUE TITLE
report event data not displaying

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#478]
**Describe the bug**
on latest yap version 3.9.4 not all of the caller event data is displaying

**What version are you running?**
3.9.4
![Screen Shot 2020-09-16 at 8 04 12 PM](https://user-images.githubusercontent.com/34245618/93404527-6bf12e00-f858-11ea-8492-a04c342d1a13.png)

**Did this happen on prior versions to the one you are running?**
it def worked on 3.9.0

![Screen Shot 2020-09-16 at 8 04 04 PM](https://user-images.githubusercontent.com/34245618/93404522-672c7a00-f858-11ea-83aa-606bcee8dea6.png)

**Comment by radius314** [comment]
Is it new records only or all records?

**Comment by pjaudiomv** [comment]
new and old records, so all

**Comment by pjaudiomv** [comment]
this worked in 3.9.3 too just confirmed

**Comment by pjaudiomv** [comment]
these are calls I just made

3.9.3

![Screen Shot 2020-09-16 at 8 25 08 PM](https://user-images.githubusercontent.com/34245618/93405385-de630d80-f85a-11ea-814b-8ffcf8550351.png)


and 3.9.4

![Screen Shot 2020-09-16 at 8 24 34 PM](https://user-images.githubusercontent.com/34245618/93405397-e458ee80-f85a-11ea-903d-0f613d9d78c4.png)

**Comment by radius314** [comment]
Two different versions pointed to the same database?


From: pjaudiomv <notifications@github.com> <notifications@github.com>
Reply: bmlt-enabled/yap
<reply@reply.github.com>
<reply@reply.github.com>
Date: September 16, 2020 at 8:26:40 PM
To: bmlt-enabled/yap <yap@noreply.github.com> <yap@noreply.github.com>
Cc: Danny Gershman <danny.gershman@gmail.com> <danny.gershman@gmail.com>,
Assign <assign@noreply.github.com> <assign@noreply.github.com>
Subject:  Re: [bmlt-enabled/yap] report event data not displaying (#478)

these are calls I just made

3.9.3

[image: Screen Shot 2020-09-16 at 8 25 08 PM]
<https://user-images.githubusercontent.com/34245618/93405385-de630d80-f85a-11ea-814b-8ffcf8550351.png>

and 3.9.4

[image: Screen Shot 2020-09-16 at 8 24 34 PM]
<https://user-images.githubusercontent.com/34245618/93405397-e458ee80-f85a-11ea-903d-0f613d9d78c4.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/bmlt-enabled/yap/issues/478#issuecomment-693735738>, or
unsubscribe

**Comment by pjaudiomv** [comment]
yes, thats correct. a Db that had been upgraded to 3.9.4. this is happening on sezf server as well

**Comment by radius314** [comment]
Fix will be in 3.9.5, you can test here: https://archives.bmlt.app/yap/yap-1811-3aed41c250bacd748b3e21359d1d2e2beadff7c0.zip

**Comment by pjaudiomv** [comment]
I just tested and all the event data is showing up now, but the reports are a lot slower. like slower than before before

**Comment by radius314** [comment]
Ok I will take a look.

**Comment by radius314** [comment]
I have #480 to address some performance improvements.

**Comment by radius314** [comment]
You can test with https://archives.bmlt.app/yap/yap-1814-9297844b763cf4a840ac41a4e22022a597ec5bcd.zip

**Comment by radius314** [comment]
this bug is fixed in 3.9.5
