### ISSUE TITLE
4.x beta 6 override service body config for twilio webhooks not working

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#543]
**Describe the bug**
overide service body config setting not working.

**What version are you running?**
4.0 beta 6

**Did this happen on prior versions to the one you are running?**
no

**To Reproduce**
set your twilio webhook to use a service body config and alter those settings, the stock config is still used

**Expected behavior**
respects the config settings

**Comment by pjaudiomv** [comment]
for the vineyard my hooks are set to `?override_service_body_id=8`

**Comment by pjaudiomv** [comment]
> I found that greetings and voicemails greetings weren't overriding. Were you seeing something else not overriding besides this? #544

Yes specifically the greetings weren't not sure about anything else not overriding

**Comment by dgershman** [comment]
Ok the bug I found was the greetings, but other things were overriding.  The greetings are handled slightly different because there is a combination of overrides for every language set (because they can be overridden individually (as they should be).  

You can see the list of settings on the admin portal under Settings.  I'm going to push out beta7 with this fix.

**Comment by dgershman** [comment]
can you review my MR #544

**Comment by pjaudiomv** [comment]
nice I tested this with beta 7 and is working now, thanks
