### ISSUE TITLE
YAP reports

### ISSUE THREAD

**Issue by MCANAYAP** [bmlt-enabled/yap#580]
Upon running reports, the last call that shows is from 2 months ago. 

Version # v3.9.9

Not sure if this has ever happened. 

1. Go to 'reports' tab
2. Click on 'Madison County' from drop down
3. Scroll down passed the graph, under the map are the last calls received
4. Last call is not the actual last call - which has been verified by several that have received calls

Need reports to run accurately. 

![image](https://user-images.githubusercontent.com/97411209/148701816-45d20500-e39a-4c4f-907b-9f192ef24dff.png)

**Comment by dgershman** [comment]
Recommendation is to upgrade to the latest version of Yap.

**Comment by MCANAYAP** [comment]
Hey Danny,
I'm new to this commitment and need some guidance; who is, and how can I
contact the SEZF Yap to upgrade to the latest version? I was under the
impression once an update was available, we'd be notified/asked to update.

Thanks,
Jen Smith

**Comment by jbraswell** [comment]
Hi Jen. I'm the administrator of the Yap server at the SEZF. I suspect we will upgrade yap to 4.x within the next 30-60 days. I've been waiting for the 4.x series to stabilize, and it is looking good now, so we will move forward soonish.

**Comment by MCANAYAP** [comment]
Hi, is there some sort of temporary solution until then, and once we
upgrade will we be able to pull the calls since November? Anything I can do
on my end?

Thanks,
Jen Smith

**Comment by jbraswell** [comment]
I don't think there's any temporary solution between now and then. If I'm wrong, someone should jump in  

Re: the SEZF server. I'm hesitant to rush to upgrade, because it's a major upgrade, and at least a couple dozen helplines depend on the server. I want to make absolutely sure myself and the other admin are available to immediately resolve any reported outages with any helplines after the upgrade, and I'm personally slammed until February. I understand the lack of reporting is frustrating, but having a broken helpline would probably be more frustrating 😉. If you can let me know how to contact you, I'll make sure to reach out when we upgrade.

**Comment by pjaudiomv** [comment]
You can always just pull your twilio logs as well.

**Comment by MCANAYAP** [comment]
Sounds good! I think we can DL raw data. I'll try that for now.

Thanks for the prompt responses as well.
My ph# is: 516-244-4890.

Thanks,
Jen Smith

**Comment by MCANAYAP** [comment]
You are correct! That's exactly what we'll do in the meantime.

Thank you all for your service and help.

Thanks,
Jen Smith
