### ISSUE TITLE
Lack of validation on phone number(s) input causes problem with both call blasting and call timeout to voicemail.

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#702]
Server: SEZF
Service Body: Forest Area (133)
Helpline Number: [352-368-6061](tel:3523686061)

Webhooks:
Call Webhook - https://bmlt.sezf.org/zonal-yap/index.php?override_tomato_helpline_routing=true&override_service_body_id=133
Call Status Changes - https://bmlt.sezf.org/zonal-yap/status.php?override_service_body_id=133
Message Webhook - https://bmlt.sezf.org/zonal-yap/sms-gateway.php?override_service_body_id=133

Observed behavior:
1. When I call in, press 1 for english, and press 1 to talk to someone, only one of the on-schedule volunteers is dialed (per the Reports tab, I am not sure if he's actually dialed). Call blasting is enabled, and several on-schedule volunteers have en-US selected as their language.
2. The call never goes to voicemail, even though it should after the default timeout of 20 seconds.

Expected behavior:
1. I expected all volunteers for the selected language to be ringed.
2. I expected the call to go to voicemail after 20 seconds.

**Comment by dgershman** [comment]
I saw an incorrect number, I temporarily disabled it and @jbraswell is attempting to see if that fixed it.  I see one other issue that could also be related.

**Comment by scrti** [comment]
I think this might be our intermittent issue. How did you fix it?
Could there be a problem with certain service providers?

**Comment by scrti** [comment]
I mean, it was working when the new version was installed, but calls would still ne dropped

Now, no calls are going through

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dgershman** [comment]
I’m not sure what you mean when you say “but call would still ne dropped”.  And I also don’t know what you mean when you say “no calls are going through”.  Please provide a detailed description of what is going on and forward to ***@***.***

From: scrti ***@***.***>
Date: Monday, July 24, 2023 at 12:38 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] Lack of validation on phone number(s) input causes problem with both call blasting and call timeout to voicemail. (Issue #702)
I mean, it was working when the new version was installed, but calls would still ne dropped

Now, no calls are going through

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by scrti** [comment]
When we call the helpline :

1-fr, 2-eng is ok
1-speak to a member ok
Voice prompt saying transferring the call to the service body Région du Québec ok
Then the hold music goes on and on and the call never reaches volunteer nor vocemail even through call settings are set to Call blasting, then voicemail.

Volunteers have not been receiving calls since yestersday


Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dgershman** [comment]
Ok thanks for this information.  I hope to look at this later on this evening, unless someone else is available to technically review your system.

From: scrti ***@***.***>
Date: Monday, July 24, 2023 at 12:45 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] Lack of validation on phone number(s) input causes problem with both call blasting and call timeout to voicemail. (Issue #702)
When we call the helpline :

1-fr, 2-eng is ok
1-speak to a member ok
Voice prompt saying transferring the call to the service body Région du Québec ok
Then the hold music goes on and on and the call never reaches volunteer nor vocemail even through call settings are set to Call blasting, then voicemail.

Volunteers have not been receiving calls since yestersday


Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dgershman** [comment]
validation will be in Yap 4.3.0
