### ISSUE TITLE
alerts not being cleared

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#714]
**Describe the bug**
Yap shows a warning if there is a phone number that is missing the Twilio Call Status Changes Callback status.php webhook. The warning is not removed when the webhook is added.

This seems like a low priority bug, since it's easy to work around it by manually removing the entry from the `alerts` table.

**What version are you running?**
4.2.8

**Did this happen on prior versions to the one you are running?**
don't know

**To Reproduce**
1. Remove the status.php webhook from a test number.
2. Call yap using the test number.
3. Log in to yap.  It should display a warning box next to the status box.  Log out.
4. Add the status.php webhook back to the test number.
5. Call yap again.
6. The warning is still there.

**Expected behavior**
The warning should be removed once the problem is fixed.

**Warning displayed**
Here is the text of the warning:

`{"status":true,"message":"Ready To Yap!","warnings":"+12062229379 is\/are phone numbers that are missing Twilio Call Status Changes Callback status.php webhook. This will not allow call reporting to work correctly.  For more information review the documentation page https:\/\/github.com\/bmlt-enabled\/yap\/wiki\/Call-Detail-Records.","version":"4.2.8","build":"7a01761f5cba076607a3de86db909dbed39ae914"}`

**Comment by dgershman** [comment]
Could not repro this issue.  Can you try to cause the error to occur again and then try to fix it by adding the webhook back?  Send a dump back to us.

**Comment by alanb2718** [comment]
OK, I did that and emailed the dump and config.php to you.

**Comment by dgershman** [comment]
Ok I'm not seeing any new rows in the `records` table.  Are you seeing any errors on the status callback in laravel.log?

**Comment by alanb2718** [comment]
No - I don't see any errors in larval.log from this test.

**Comment by dgershman** [comment]
Ok there are no records being created since Dec 30th in the records channel.  The status callback is what writes to this table.   So the callback isn’t firing off, which is why the alert isn’t clearing.  My thought was that there is an error, but as you mentioned, there are no errors.

From: Alan B ***@***.***>
Date: Sunday, January 29, 2023 at 6:44 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] alerts not being cleared (Issue #714)

No - I don't see any errors in larval.log from this test.

**Comment by alanb2718** [comment]
I just remembered this version includes the code for PR #713 ... so I wondered if that could be the reason records aren't being created.  So I installed a fresh copy of yap, without the PR -- I'm still seeing the same behavior as reported though.  And still no records since Dec 30.

**Comment by dgershman** [comment]
are you using specific credentials in the service body confit?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alanb2718** [comment]
The configuration for the service body (WNIRNA) includes the twilio account SID and auth token.  This overrides the settings in config.php.  (Is this what you're asking?)

**Comment by dgershman** [comment]
Yes.  Are you setting a service body id query string on your callback url?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alanb2718** [comment]
yes:

`https://bmlt.wszf.org/yap/status.php?override_service_body_id=2`

**Comment by dgershman** [comment]
Can you email me your Laravel.log file?

From: Alan B ***@***.***>
Date: Sunday, January 29, 2023 at 7:33 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] alerts not being cleared (Issue #714)

yes:

https://bmlt.wszf.org/yap/status.php?override_service_body_id=2

**Comment by alanb2718** [comment]
The laravel.log file is empty right now for the test server, since I just installed a fresh copy.  Creating the error by omitting the callback didn't cause anything to get logged.

**Comment by dgershman** [comment]
Something then seems misconfigured in writing to the log file.  There should be an error generated by going to the status.php page without any querystring parameters from your web browser.

From: Alan B ***@***.***>
Date: Sunday, January 29, 2023 at 7:51 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] alerts not being cleared (Issue #714)

The laravel.log file is empty right now for the test server, since I just installed a fresh copy. Creating the error by omitting the callback didn't cause anything to get logged.

**Comment by alanb2718** [comment]
I think I found something.  This is for a zonal server. The zone doesn't pay for Twilio accounts for any of the service bodies; that is the responsibility of regions or areas in the zone.  There is a zonal Twilio account, whose SID and auth code is in the config.php file.  It used to have a test number -- but this was getting charged every month for not doing anything, so we left the account open but released the number.  This seems to have caused the problem.  I just tried buying a random number on the zone's account and set that up.  Now alerts are being cleared correctly.

So does the zone need to have a Twilio number for this to work correctly, even if it's never used?

**Comment by dgershman** [comment]
Perhaps.  Can you try this with your Twilio Test Credentials?

I know the SEZF uses the same approach (not sure which creds they use).

https://www.twilio.com/docs/iam/test-credentials

--Danny

From: Alan B ***@***.***>
Date: Monday, January 30, 2023 at 1:06 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] alerts not being cleared (Issue #714)

I think I found something. This is for a zonal server. The zone doesn't pay for Twilio accounts for any of the service bodies; that is the responsibility of regions or areas in the zone. There is a zonal Twilio account, whose SID and auth code is in the config.php file. It used to have a test number -- but this was getting charged every month for not doing anything, so we left the account open but released the number. This seems to have caused the problem. I just tried buying a random number on the zone's account and set that up. Now alerts are being cleared correctly.

So does the zone need to have a Twilio number for this to work correctly, even if it's never used?

**Comment by alanb2718** [comment]
Yap is not happy with the Twilio Test Credentials.  I put them in config.php for the test yap server and the login page (before logging in) says "Status: Problem".  Clicking that gives:

`{"status":false,"message":"Twilio Rest Error: [HTTP 403] Unable to fetch page: Resource not accessible with Test Account Credentials","warnings":"+12062229379 is\/are phone numbers that are missing Twilio Call Status Changes Callback status.php webhook. This will not allow call reporting to work correctly.  For more information review the documentation page https:\/\/github.com\/bmlt-enabled\/yap\/wiki\/Call-Detail-Records.","version":"4.2.8","build":"7a01761f5cba076607a3de86db909dbed39ae914"}`

If I go ahead and log in, I still see the warning about the missing status changes callback, even though I put the status changes callback back.  The warning is also still in the alerts table, and the records table still doesn't include anything since 12/30.

But I can still call the test number and I get the meeting results back as expected.

**Comment by dgershman** [comment]
There some API calls that will fail because of the limited capability of test credentials, I forgot there are some additional lookups that happen in the Upgrade Advisor that would cause that to fail.  Interesting that you still don’t see records in the records table added.  You said before when you added a phone number that the error cleared?

From: Alan B ***@***.***>
Date: Monday, January 30, 2023 at 2:43 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] alerts not being cleared (Issue #714)

Yap is not happy with the Twilio Test Credentials. I put them in config.php for the test yap server and the login page (before logging in) says "Status: Problem". Clicking that gives:

{"status":false,"message":"Twilio Rest Error: [HTTP 403] Unable to fetch page: Resource not accessible with Test Account Credentials","warnings":"+12062229379 is\/are phone numbers that are missing Twilio Call Status Changes Callback status.php webhook. This will not allow call reporting to work correctly. For more information review the documentation page https:\/\/github.com\/bmlt-enabled\/yap\/wiki\/Call-Detail-Records.","version":"4.2.8","build":"7a01761f5cba076607a3de86db909dbed39ae914"}

If I go ahead and log in, I still see the warning about the missing status changes callback, even though I put the status changes callback back. The warning is also still in the alerts table, and the records table still doesn't include anything since 12/30.

But I can still call the test number and I get the meeting results back as expected.

**Comment by alanb2718** [comment]
Yes - I tried adding a phone number to the zone's twilio account, and then everything seems to be working ok.  I removed the status callback from the test number yet again, called, saw the warning, added the status callback back again, called again, and the warning cleared.  Also the call was in the records table.

**Comment by dgershman** [comment]
Ok I will take this new information and attempt to reproduce on my end.

From: Alan B ***@***.***>
Date: Monday, January 30, 2023 at 2:51 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Comment ***@***.***>
Subject: Re: [bmlt-enabled/yap] alerts not being cleared (Issue #714)

Yes - I tried adding a phone number to the zone's twilio account, and then everything seems to be working ok. I removed the status callback from the test number yet again, called, saw the warning, added the status callback back again, called again, and the warning cleared. Also the call was in the records table.

**Comment by dgershman** [comment]
I still could not reproduce the error.

**Comment by alanb2718** [comment]
Thanks for continuing to investigate.  Since there is a workaround, I guess I will just leave this as is for now, and not worry about it.

**Comment by dgershman** [comment]
Does this still happen?

**Comment by alanb2718** [comment]
Yes.  I just tested with yap 4.3.0-beta8, and the warning does not get cleared.  But as before this seems low priority to fix, since there is a straightforward workaround.

**Comment by dgershman** [comment]
Can you resend me your database?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alanb2718** [comment]
OK done.

**Comment by dgershman** [comment]
@alanb2718 I added some additional logging here, can you try this out? https://s3.amazonaws.com/archives.bmlt.app/yap/yap-379-1fec2f885684985215826f7b8c6a370e160d9f8a.zip

**Comment by alanb2718** [comment]
I tested it - everything checks out and I think you can close this ticket. Specifically, I set up a test number and made sure it was working. Then I removed the call status changes callback.  This gave the warning, and also put something in the larval log file.  Then I added the call status changes callback again, and the warning cleared.

**Comment by dgershman** [comment]
Cool
