### ISSUE TITLE
Wrong translation in french

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/yap#843]
**Describe the bug**
In French, when you press 2 to find a meeting, it asks you (in French) "for which City".

**What version are you running?**
4.2.10

**Did this happen on prior versions to the one you are running?**
No

**To Reproduce**
1. Dial the helpline
2. the one for french and dial two to find a meeting
3. After this message, if you tell the city, it will looks for meetings
4. No error

**Expected behavior**

To ask which ville

**Comment by dgershman** [comment]
You must have some setting overrided in your configuration somewhere, because the default translation in English is "city or county", and it's not saying that.  Look at your config.php settings or if you have any overrides at the service body level.  The short answer is that this is the translation, which is correct.  

https://github.com/bmlt-enabled/yap/blob/main/lang/en-US.php#L32
https://github.com/bmlt-enabled/yap/blob/main/lang/fr-CA.php#L31

Documentation: https://yap.bmlt.app/general/language-options/
